// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zBpkD6qLK8olO98OKnwg66sm1G36BxI',
    appId: '1:217409476638:web:b8624687484d0f37ff360f',
    messagingSenderId: '217409476638',
    projectId: 'examinar-1b919',
    authDomain: 'examinar-1b919.firebaseapp.com',
    storageBucket: 'examinar-1b919.firebasestorage.app',
    measurementId: 'G-NDTQZ8SC0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ2S4PO9h9So7lLGeKhhlJ8LWhH7cJPwY',
    appId: '1:217409476638:android:45cacfec7c8b2834ff360f',
    messagingSenderId: '217409476638',
    projectId: 'examinar-1b919',
    storageBucket: 'examinar-1b919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4681s1HuI1MNGHCB2aCtpQxm_MvCA6uQ',
    appId: '1:217409476638:ios:b1ef8cd2388509e5ff360f',
    messagingSenderId: '217409476638',
    projectId: 'examinar-1b919',
    storageBucket: 'examinar-1b919.firebasestorage.app',
    iosBundleId: 'com.examcommandcenter.examCommandCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4681s1HuI1MNGHCB2aCtpQxm_MvCA6uQ',
    appId: '1:217409476638:ios:b1ef8cd2388509e5ff360f',
    messagingSenderId: '217409476638',
    projectId: 'examinar-1b919',
    storageBucket: 'examinar-1b919.firebasestorage.app',
    iosBundleId: 'com.examcommandcenter.examCommandCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zBpkD6qLK8olO98OKnwg66sm1G36BxI',
    appId: '1:217409476638:web:31dbc9f60136765aff360f',
    messagingSenderId: '217409476638',
    projectId: 'examinar-1b919',
    authDomain: 'examinar-1b919.firebaseapp.com',
    storageBucket: 'examinar-1b919.firebasestorage.app',
    measurementId: 'G-CQB3W8SNFR',
  );
}
